kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: home-v1-binding
  namespace: mesh_name
spec:
  virtualDeployment:
    ref:
      name: home-v1
      namespace: mesh_name
  target:
    service:
      ref:
        name: home-v1
        namespace: mesh_name
---
kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: home-v2-binding
  namespace: mesh_name
spec:
  virtualDeployment:
    ref:
      name: home-v2
      namespace: mesh_name
  target:
    service:
      ref:
        name: home-v2
        namespace: mesh_name
---
kind: VirtualDeploymentBinding
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: price-v1-binding
  namespace: mesh_name
spec:
  virtualDeployment:
    ref:
      name: price-v1
      namespace: mesh_name
  target:
    service:
      ref:
        name: price-v1
        namespace: mesh_name
---