{
 "title": "OCI Service Mesh Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "successRateGranularity", "label": "Success Rate Granularity", "query": "1m,5m,10m,15m" },
   { "name": "latencyGranularity", "label": "Latency Granularity", "query": "1m,5m,10m,15m" }
  ]
 },
 "panels": [
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(rate(envoy_http_ingress_http_downstream_rq_2xx{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_3xx{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_4xx{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity])) by (virtual_service_name)) / sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity])) by (virtual_service_name), 1)",
     "legendFormat": "home"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_ingress_http_downstream_rq_time_bucket{virtual_service_name=\"mesh_name/home\"}[$latencyGranularity])) by (le))",
     "legendFormat": "home"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(rate(envoy_http_ingress_http_downstream_rq_2xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_3xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_4xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity])) by (virtual_deployment_name)) / sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity])) by (virtual_deployment_name), 1)",
     "legendFormat": "v1"
    },
    {
     "expr": "clamp_max((sum(rate(envoy_http_ingress_http_downstream_rq_2xx{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_3xx{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity]) + rate(envoy_http_ingress_http_downstream_rq_4xx{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity])) by (virtual_deployment_name)) / sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity])) by (virtual_deployment_name), 1)",
     "legendFormat": "v2"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_ingress_http_downstream_rq_time_bucket{virtual_deployment_name=\"mesh_name/home-v1\"}[$latencyGranularity])) by (le))",
     "legendFormat": "v1"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_ingress_http_downstream_rq_time_bucket{virtual_deployment_name=\"mesh_name/home-v2\"}[$latencyGranularity])) by (le))",
     "legendFormat": "v2"
    }
   ]
  },
  {
   "title": "Egress Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(rate(envoy_http_egress_http_downstream_rq_2xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity]) + rate(envoy_http_egress_http_downstream_rq_3xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity]) + rate(envoy_http_egress_http_downstream_rq_4xx{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity])) by (virtual_deployment_name)) / sum(rate(envoy_http_egress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity])) by (virtual_deployment_name), 1)",
     "legendFormat": "v1"
    },
    {
     "expr": "clamp_max((sum(rate(envoy_http_egress_http_downstream_rq_2xx{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity]) + rate(envoy_http_egress_http_downstream_rq_3xx{virtual_deployment_name=\"mesh_name/reviews-v2\"}[$successRateGranularity]) + rate(envoy_http_egress_http_downstream_rq_4xx{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity])) by (virtual_deployment_name)) / sum(rate(envoy_http_egress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity])) by (virtual_deployment_name), 1)",
     "legendFormat": "v2"
    }
   ]
  },
  {
   "title": "Traffic Split",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v1\"}[$successRateGranularity])) by (virtual_service_name) / sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity])) by (virtual_service_name)",
     "legendFormat": "v1"
    },
    {
     "expr": "sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_deployment_name=\"mesh_name/home-v2\"}[$successRateGranularity])) by (virtual_service_name) / sum(rate(envoy_http_ingress_http_downstream_rq_total{virtual_service_name=\"mesh_name/home\"}[$successRateGranularity])) by (virtual_service_name)",
     "legendFormat": "v2"
    }
   ]
  }
 ]
}